apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gemini-api-ingress
  namespace: ai
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: ai.kaayaka.in
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gemini-backend
                port:
                  number: 8000
