apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gemini-ingress
  namespace: ai
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/enable-buffering: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ai.kaayaka.in
      secretName: ai-kaayaka-tls
  rules:
    - host: ai.kaayaka.in
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gemini-backend
                port:
                  number: 8000

          - path: /_next
            pathType: Prefix
            backend:
              service:
                name: gemini-frontend
                port:
                  number: 80

          - path: /static
            pathType: Prefix
            backend:
              service:
                name: gemini-frontend
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: gemini-frontend
                port:
                  number: 80
